### ISSUE TITLE
Some files not sending properly for the TI-84+ CE(-T Python Edition)

### ISSUE THREAD

**Issue by PrivacyDragon** [Timendus/ticalc.link#8]
There are some files that are being sended properly.
I've made a list of files that _do_ work and files that do _not_ work.
I think that the problem has something to do with the file size.
The files that are being sent are all small...

### files that work: ###
- BATTERY (https://www.ticalc.org/archives/files/fileinfo/475/47544.html) [Only after replugging the cable, if tried another file first]
- θLIGHT (Within the CLOCKCE zip) [DOES send, but NOT correctly. the theta is changed into another symbol]
- θDARK (Within the CLOCKCE zip) [DOES send, but NOT correctly. the theta is changed into another symbol]

### files that don't work: ###
- BOARDCE (https://www.ticalc.org/archives/files/fileinfo/475/47549.html) [does send sometimes, but then just as empty program]
- CLOCKCE (https://www.ticalc.org/archives/files/fileinfo/475/47562.html) [does send sometimes, but then just as empty program]
- STORYCE (https://www.ticalc.org/archives/files/fileinfo/475/47553.html) [[does send sometimes, but then just as empty program]
- RNDMNMBR (https://www.ticalc.org/archives/files/fileinfo/475/47535.html) [gives also an error to the user]

**Comment by debrouxl** [comment]
With the TI-Z80 models in direct USB mode, 89T in DUSB mode, TI-eZ80 models and Nspire models, it's _mostly_ possible to make do with supporting only UTF-8. But still - in general, proper handling of the specific charsets used by TI graphing calculators requires a whole layer of code. And libticonv isn't perfect.

**Comment by adriweb** [comment]
A good test might be to send a program containing all possible tokens. ALLTOKS or similar, I have that somewhere....

**Comment by Timendus** [comment]
Hey @PrivacyDragon, thanks for testing and the nice list. Looks like θ isn't being sent properly in the file name, and if @adriweb is right and file names can only contain A-Z, 0-9 and θ then that's probably a pretty simple thing to fix. I'll just need to find the right byte to replace those with.

>θLIGHT (Within the CLOCKCE zip) [DOES send, but NOT correctly. the theta is changed into another symbol]
>θDARK (Within the CLOCKCE zip) [DOES send, but NOT correctly. the theta is changed into another symbol]

I'm assuming that you mean to say that **only** the name is sent incorrectly? Otherwise the files are in good working condition?

For the larger files that don't send properly I'll have to take a better look at the difference between the binaries. A first careful hypothesis I have is that I think there may be a problem with the file's properties like archived or protected.

@debrouxl I'm assuming that if I just send over the plain binary data (the data inside the program) untouched and without interpretation, that character encoding shouldn't be an issue, right?

**Comment by debrouxl** [comment]
You're right that the data inside the program should be sent untouched... but that won't save you from having to deal with (a subset of) the file names' encoding / tokenization schemes, even if you don't implement the 73, 83, 85, 86 file formats for now, which is the right thing to do - focusing on newer models first :)

To elaborate on my previous message, dealing with file name encoding / tokenization matters for both display and transfer functionality, for instance (and probably not limited to):
* sending to a 84+ through DUSB data from a 83+ / 84+ program stored in a 83+ format with which the 84+ is compatible. For instance, the names of Pic0-9 (reasonably frequently used in games or school programs), GDB0-9 and Str0-9 are tokenized.
* sending or receiving FlashApps performing language localization: at least the Spanish language localization FlashApp's name contains a special international character, n tilde;
* sending or receiving variables containing Greek character names other than θ, some of which are definitely valid in file names at least on the TI-68k series. I've just created two variables named (greek beta) and (greek gamma) in TIEmu, then used TILP to perform a dirlist through the virtual cable and DBUS protocol: TILP displayed the expected appropriate greek letters.

Granted, making it possible to reliably transfer larger files whose names do not contain special characters will arguably be more useful to more users than making it possible to reliably transfer files whose names contain special characters or tokens, so I'd argue that the former sub-task should have higher priority than the latter; however, both are necessary to provide full-featured transfer capability :)

The files of libticonv most relevant to you are charset.cc and filename.cc: https://github.com/debrouxl/tilibs/tree/experimental2/libticonv/trunk/src .

**Comment by commandblockguy** [comment]
I've created two PRs on the USB library that should fix the issues with certain programs not being sent, but not the issue with the filenames.

**Comment by Timendus** [comment]
@commandblockguy's PRs have been merged and deployed on [ticalc.link](https://ticalc.link). The file name issue is still there, but more files should now send successfully.

**Comment by PrivacyDragon** [comment]
I can confirm that more files work now. It even worked with sending the clibs, though that didn't succeed the first time. My calculator started defragmenting the first time... I don't know of that is because there was too much on my calculator or if it was because it had to overwrite the clibs. One of the libs was messed up after the first time. It was just sixteen bytes...
I deleted that one, deleted a program and tried again. Then it worked.
I would have to test a bit more to see if I can find out what caused it to fail the first time.

**Comment by Timendus** [comment]
I'm closing this issue for now. Feel free to open another one if you figure out what caused the defragmenting!
